name: s5cmd
description: Setup s5cmd cli on GitHub Actions runners
branding:
  icon: upload-cloud
  color: purple

inputs:
  version:
    description: Version of s5cmd to install
    required: false
    default: latest

runs:
  using: node24
  main: dist/index.mjs
